# Generated by Django 3.2.7 on 2021-10-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0002_foods_prise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='user',
            new_name='users',
        ),
    ]
