# Generated by Django 3.2.7 on 2021-10-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0003_auto_20211025_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='address',
            new_name='city',
        ),
        migrations.AddField(
            model_name='addresses',
            name='line1',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresses',
            name='line2',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresses',
            name='state',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresses',
            name='zip',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
