# Generated by Django 3.2.7 on 2021-10-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0004_auto_20211025_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='city',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='line1',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='line2',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='state',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='zip',
        ),
    ]
